# Generated by Django 4.2.11 on 2024-04-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homemaker',
            fields=[
                ('Homemaker_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100, null=True)),
                ('Kitchen_name', models.CharField(max_length=100, null=True)),
                ('Contact', models.CharField(max_length=10, null=True)),
                ('Email_Id', models.CharField(max_length=100, null=True)),
                ('Kitchen_Address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Item_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Item_name', models.CharField(max_length=100, null=True)),
                ('Item_price', models.IntegerField(default=1000)),
                ('Item_quantity', models.IntegerField(default=1000)),
                ('Homemaker_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='food.homemaker', verbose_name='Homemaker')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100, null=True)),
                ('Contact', models.CharField(max_length=10, null=True)),
                ('Email_Id', models.CharField(max_length=100, null=True)),
                ('Password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_Id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(verbose_name='Date')),
                ('order_total_price', models.IntegerField(default=1000)),
                ('Item_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='food.item', verbose_name='Item')),
                ('User_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='food.users', verbose_name='User')),
            ],
        ),
    ]
